Feat/ creating product section and other stuff
MagnusHLund/H2_Davids_book_club pull request #20
Opened 2024-06-19 10:20 UTC by MarcusL00

2024-06-19 10:23 UTC, MagnusHLund commented on Web_client/src/components/inputs/QuantityButton.scss
best SCSS to date

2024-06-19 10:42 UTC, MagnusHLund requested changes

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/inputs/QuantityButton.tsx
> +  return (
Missing functionality for buttons.

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/inputs/QuantityButton.tsx
> +      <Button></Button>
Missing classnames

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/ProductSection.scss
> +body{
Put this within app.scss
Also make a variable for it, so all the color variables are together.

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/ProductSection.scss
> +.product-section__upper {
Du skal udnytte dine klasse navne i scss.
Her er det eksempel jeg gav til mr robes.

![image](https://github.com/MagnusHLund/H2_Davids_book_club/assets/124877369/e83a3662-a1d4-4973-9c6d-fd09eb0cfe76)

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/ProductSection.scss
> +.product-section__upper__pic {
product-section__upper--image?

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/sub sections/Product section/ProductAdditionalInfoSection.scss
> +.ProductInfo{
Not very BEM

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/sub sections/Product section/ProductAdditionalInfoSection.tsx
> +    <div className="ProductInfo">
Hvor henne er dataen for informationerne?
Du kan lave noget placeholder data.

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/sub sections/Product section/ProductImageSection.tsx
> +function ProductImageSection() {
Mangler funktionalitet til at skifte mellem billeder.
Lav noget dummy data, med 2 billeder og så skift imellem dem, ved brug af knapperne.

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/sections/sub sections/Product section/ProductOverviewSection.tsx
> +
Du skal udskifte det her kode med QuantityButton.

2024-06-19 10:42 UTC, MagnusHLund commented on Web_client/src/components/inputs/QuantityButton.tsx
> +const QuantityButton: React.FC<IQuantityButton> = ({ defaultValue = '' }) => {
Giver det ikke mere mening at kalde det for "QuantitySelector"?
Man kan jo vælge quantity med brug af text input og 2 knapper.

2024-06-19 11:51 UTC, MarcusL00 commented on Web_client/src/components/sections/sub sections/Product section/ProductAdditionalInfoSection.tsx
> +    <div className="ProductInfo">
i tried

2024-06-20 11:44 UTC, MagnusHLund requested changes

2024-06-20 11:44 UTC, MagnusHLund commented on Web_client/src/components/inputs/QuantitySelector.scss
> +.text-input_box{
.text-input_box shouldnt be alone.
It needs friends too! Perhaps it will have better luck making friends, with another name.

Change its name to quantity-selector__text or quantity-selector__input--text or something.
Based on the other names, quantity-selector__text would fit best.

Now with its new name, include it in the friend group!
.quantity-selector { 
&__text {}
}

2024-06-20 11:44 UTC, MagnusHLund commented on Web_client/src/components/inputs/QuantitySelector.tsx
> +    if (!isNaN(newValue) && newValue >= 1) {
Perhaps it would be better to have a constant, which makes sure its above the minimum value.
Magic numbers are whack.

2024-06-20 11:44 UTC, MagnusHLund commented on Web_client/src/components/inputs/TextInput.tsx
> +  onChange: (e: React.ChangeEvent<HTMLInputElement>) => void
Put the onChange within StandardInputProps.

2024-06-20 11:44 UTC, MagnusHLund commented on Web_client/src/components/sections/sub sections/Product section/ProductImageSection.tsx
> +function ProductImageSection() {
still missing functionality

2024-06-20 11:50 UTC, MarcusL00 commented on Web_client/src/components/sections/sub sections/Product section/ProductAdditionalInfoSection.scss
> +.ProductInfo{
fixed

2024-06-21 07:52 UTC, merged