Feat/homepagelook done
MagnusHLund/H2_Davids_book_club pull request #6
Opened 2024-04-25 11:27 UTC by Jorjo6712

I've made all of the necessary front UI aside from a drop-down and general interactivity, with input boxes and buttons that will come with the next feature.

Dependencies with this feature: react-icons

2024-04-25 19:53 UTC, MagnusHLund requested changes

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/components/Image.tsx
> +        <img src={ imageSrc }   className="Image" />
Classnames are lower case, with BEM.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/components/ProductDisplay.tsx
> +interface IProductDisplay {
Unused interface.
Is it gonna be implemented in the future?

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/components/ProductDisplay.tsx
> +const numberOfProducts = 7
Put this const inside the component.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/components/ProductDisplay.tsx
> +            {Array.from({ length: numberOfProducts }, () => (
Personally i think the .map function is a better approach for this. More elegant.
If you disagree, then feel free to keep it.
Lets have a chat about it, if you have any questions. 
Array.from just looks janky, imo.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/components/SearchBox.tsx
>  const SearchBox: React.FC<ISearchBox> = ({ placeholder }) => {
### Same comment as for button.tsx
I think that you will get an undefined placeholder, if you create the Button without specifying a value for the placeholder. Feel free to test it, incase I am wrong. Usually I would say ({ placeholder="" }) to assign a default value.

But maybe an empty placeholder is not the best approach.
Why would you ever want a button without text?

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/scss/Button.scss
> +        transform: translateY(4px);
I ran the project, because of this line.
4px seems like a bit much, but it might be because the pixels are smaller on your laptop than on my monitor at home. I prefer 2 pixels, at home. I have not seen it on my laptop screen.
I will run it tomorrow. I will let you know what I think and lets see if we can agree on a pixel size.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/scss/Header.scss
Overall header css comment.
The header does not scale at all, with smaller screen sizes.
Try using different screen sizes and redo some of the header styling.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/scss/Header.scss
> +        flex-direction: row;
Flex-direction: row; does nothing here, unless i am missing something.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/scss/Header.scss
> +        scale: 250%;
250% size increase?
Do you want a bigger picture?

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/scss/Header.scss
Overall css comment again.
I just noticed that the scss files are in a scss folder.
Just leave them next to the component that it connected to. Same folder.
Makes it very fast to find, when working on that component in the future.

That is also another reason why i use scss. 
Both the react icon and regular css icon is blue. Faster to navigate when scss is red.
Could get other icons, but I fear I will run into the same issue with other file types, so why bother.

2024-04-25 19:53 UTC, MagnusHLund commented on Web_client/src/scss/Image.scss
> +.image {
You are not using this styling, because you made the class "Image" uppercase instead of "image" lowercase.
Made another comment about that too, in the Image component. Change it to be lowercase, in the component classname.

2024-04-25 20:09 UTC, MagnusHLund commented on Web_client/src/components/Image.tsx
> +        <img src={ imageSrc }   className="Image" />
<img> tags should always have an "alt='description of the image'" attribute. 
For the blind people, listening to the screen.

2024-04-25 20:13 UTC, Jorjo6712 commented on Web_client/src/components/ProductDisplay.tsx
> +interface IProductDisplay {
I'm not sure depends from where we're passing data although most likely not it originally was more of copy pasting the structure of tsx. So not for now.

2024-04-25 20:16 UTC, Jorjo6712 commented on Web_client/src/components/ProductDisplay.tsx
> +const numberOfProducts = 7
This is for test purposes, I'll rewrite any logic in this component so it satisfies Endpoint return key:value pairs from the api. Assuming it returns json ofc.

2024-04-25 20:22 UTC, Jorjo6712 commented on Web_client/src/scss/Header.scss
> +        flex-direction: row;
May i suggest a purging tool for overridden css? PurgeCSS.

2024-04-25 20:23 UTC, Jorjo6712 commented on Web_client/src/scss/Header.scss
I haven't looked into responsiveness yet, I will no worries.

2024-04-25 20:27 UTC, Jorjo6712 commented on Web_client/src/Images/DavidsBookClub.png
To be fair I figured react generated one itself like in Vue and I was going to put it there but I looked and saw none, so ig I have to make it myself???

2024-04-25 20:30 UTC, Jorjo6712 commented on Web_client/src/scss/Header.scss
> +        scale: 250%;
It's a compromise I had to make for it to fit relatively well in the header without breaking it and making it abhorrent, but maybe idk. Personally I think it's fine as it is rn.

2024-04-26 06:07 UTC, MagnusHLund commented on Web_client/src/Images/DavidsBookClub.png
It does get generated, at least with vite.
I guess I might have deleted it, early on in the project, when i removed the default project.

2024-04-26 06:08 UTC, MagnusHLund commented on Web_client/src/scss/Header.scss
> +        flex-direction: row;
Yea, you can install that.

2024-06-17 19:37 UTC, MagnusHLund requested changes

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/App.tsx
> +import './components/App.scss'
You have accidentally left App.scss in the wrong folder. The file path should always be ./file.scss

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/Sections/Home.tsx
This is still a component, which is why it should be within /src/components/sections. 
My personal opinion. fight me about it, if you disagree.

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/Button.tsx
>  const Button: React.FC<IButton> = ({ placeholder }) => {
You still have to do ({ placeholder = "" })

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/ProductDisplay.tsx
> +const numberOfProducts = 7
The API does return Json, yes. I am fine letting it come through PR with this const value.
Resolve the conversation when you have read it.

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/ProductDisplay.tsx
> +            {Array.from({ length: numberOfProducts }, () => (
Any defense to say for Array.from?

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/SearchBox.tsx
>  const SearchBox: React.FC<ISearchBox> = ({ placeholder }) => {
Again, same comment as for Button.tsx

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/WelcomeAndMotto.scss
> +        font-weight: normal;
Is there some styling i am missing? 
You set font-weight to normal, but that is the default font-weight. Is it set anywhere else, to another font-weight?

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/WelcomeAndMotto.tsx
> +function WelcomeAndMotto() {
Maybe change the component name to something better?
If you would define it as a form of banner, then WelcomeBanner? Or maybe just "Greeting"? It is a form of greeting, i suppose. It is hard to find a good name for this component, i will admit.

2024-06-17 19:37 UTC, MagnusHLund commented on Web_client/src/components/WelcomeAndMotto.tsx
> +        <div className='welcomeAndMotto'>
class name is wrong. Both that its a shit class name and because "welcome-and-motto" would be correct for BEM. But the classname itself is shit. Maybe a better classname can be made, once there is a better component name.
You are free to use one of the 2 i mentioned in my other comment. "WelcomeBanner" or "Greeting". Otherwise you can make up your own, if you think you can do better.

2024-06-18 06:43 UTC, Jorjo6712 commented on Web_client/src/components/WelcomeAndMotto.scss
> +        font-weight: normal;
It prevents the text from being bold. I don't know what causes it to be styled bold, so I'll leave it like this.

2024-06-18 07:46 UTC, MagnusHLund requested changes

2024-06-18 07:46 UTC, MagnusHLund commented on Web_client/src/components/Header.tsx
> +                    <LuShoppingBasket className='header__button-container__icon'/>
header__basket-icon

2024-06-18 08:05 UTC, merged